[workspace]
members = ["crates/habitos-core", "src-tauri"]
default-members = ["crates/habitos-core"]
resolver = "2"

[workspace.package]
version = "0.1.5"
license = "MIT"
authors = ["NotSatoriKomeiji"]
edition = "2021"
rust-version = "1.90"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
