<script lang="ts">
 import {onMount} from 'svelte';import Icon from './Icon.svelte';import Logo from './Logo.svelte';import LocalClock from './LocalClock.svelte';import QuickApps from './QuickApps.svelte';import AssistPanel from './AssistPanel.svelte';import ExperiencePanel from './ExperiencePanel.svelte';import StartupControl from './StartupControl.svelte';import {command,native,watch,floating,tray} from './bridge';import type {Status,RankedApp,Settings} from './types';
 let data:Status|null=null,tab='home',busy=false,error='',notice='',noticeKind='添加结果',savedOpen=false,query='',website='',confirmForget=false,revision=0;
 // Native toggles own savedOpen; only a new non-empty search explicitly reopens it.
 $: searchQuery=query.trim().toLowerCase();
 function search(event:Event){query=(event.currentTarget as HTMLInputElement).value;if(query.trim())savedOpen=true;}
 const nav=[{id:'home',label:'首页',icon:'home'},{id:'adjust',label:'自动调节',icon:'volume'},{id:'words',label:'快速词',icon:'sparkle'},{id:'settings',label:'设置',icon:'settings'}];
 async function action(name:string,args:Record<string,unknown>={}){if(busy)return;busy=true;error='';notice='';revision++;try{data=await command(name,args);if(name==='add_target'||name==='add_website'||name==='remove_target'||name==='open_target'){notice=data.message;noticeKind=name==='remove_target'?'移除结果':name==='open_target'?'启动结果':'添加结果';if(name!=='open_target')savedOpen=true;}}catch(e){error=String(e);}finally{busy=false;}}
 function settings(patch:Partial<Settings>){if(data)return action('save_settings',{settings:{...data.settings,...patch}});}
 const open=(app:RankedApp)=>action('open_target',{id:app.app_id,session:data?.current?.session??''});
 const openSaved=(id:string)=>action('open_target',{id,session:data?.current?.session??''});
 onMount(()=>{let alive=true,stop:(()=>void)|undefined;command('status').then(s=>{if(alive)data=s;}).catch(e=>error=String(e));watch(s=>{if(alive&&!busy)data=s;}).then(s=>stop=s);const refresh=()=>{const r=revision;command('status').then(s=>{if(alive&&!busy&&r===revision)data=s;}).catch(()=>{});};document.addEventListener('visibilitychange',refresh);return()=>{alive=false;stop?.();document.removeEventListener('visibilitychange',refresh);};});
</script>
{#if floating}
 <div class="overlay-root" aria-label="常用应用"><div class="popup-header"><div class="popup-brand"><Logo/><strong>Satori</strong></div><LocalClock/></div><p class="popup-caption">已添加的快捷应用</p>{#if notice}<p class="popup-caption" role="status" aria-label={noticeKind}>{notice}</p>{/if}{#if data?.experience.question}<p class="popup-caption">有一个新情况想和你确认</p><button class="text-button" on:click={()=>action('open_panel')}>查看学习建议</button>{:else}<QuickApps apps={data?.home_apps??[]} disabled={busy||!data} onOpen={open} onAdd={()=>action('add_target')}/>{/if}<div class="popup-footer"><button class="text-button" on:click={()=>action('open_panel')}>打开面板</button><button class="text-button" on:click={()=>action('hide_popup')}>收起</button></div>{#if error}<p role="alert">{error}</p>{/if}</div>
{:else}
<div class="shell"><aside class="sidebar"><div class="brand"><Logo/><div>Satori</div></div><div class="nav-caption">让电脑更懂你</div><nav aria-label="主导航">{#each nav as n}<button class:active={tab===n.id} on:click={()=>{tab=n.id;error='';}}><Icon name={n.icon}/><span>{n.label}</span>{#if tab===n.id}<span class="nav-dot"></span>{/if}</button>{/each}</nav><div class="sidebar-note"><span class="tiny-dot"></span>在这台电脑上学习<small>你来使用，Satori 慢慢记住。</small></div><div class="version">v0.1.4 <span>ALPHA</span></div></aside>
<main><header><div class="breadcrumb">Satori <span>/</span> {nav.find(n=>n.id===tab)?.label}</div><div class="header-right"><span class="badge" class:muted={data?.settings.paused}>{data?.settings.paused?'已暂停':'陪伴中'}</span><button class="text-button" disabled={busy||!data} on:click={()=>data&&settings({paused:!data.settings.paused})}>{data?.settings.paused?'继续运行':'暂停助手'}</button></div></header><div class="content">
{#if data?.demo}<div class="demo-banner"><span class="demo-label">演示模式</span><span>此处仅预览功能，不会改变真实音量、亮度或监听输入。</span></div>{/if}{#if error}<div class="error" role="alert">{error}</div>{/if}
{#if !data}<p>正在连接 Satori…</p>
{:else if tab==='home'}
 <section class="page-heading"><div><LocalClock/><p>{data.settings.paused?'助手已暂停。点「继续运行」即可恢复。':'照常使用电脑就好，Satori 会记住你常用的应用和调节习惯。'}</p></div></section>
 <section class="card"><div class="card-heading"><h2>常用应用与网站</h2><button class="text-button" disabled={busy} on:click={()=>action('add_target')}>添加应用</button></div><input class="search" aria-label="快速搜索" placeholder="找一个常用应用或网站…" value={query} on:input={search}><QuickApps apps={data.home_apps.filter(a=>a.name.toLowerCase().includes(searchQuery))} disabled={busy} onOpen={open} onAdd={()=>action('add_target')}/>{#if notice}<p class="friendly-note" role="status" aria-label={noticeKind}>{notice}</p>{/if}{#if data.targets.length}<details class="saved-targets" bind:open={savedOpen}><summary>已添加的应用与网站（{data.targets.length}）</summary><p class="friendly-note">这里列出全部已保存的应用与网站；上方显示六个常用快捷入口。暂停学习或关闭主动建议不会隐藏这些快捷入口。移除仅从 Satori 列表删除，不会删除本机 exe。</p><ul aria-label="已添加目标">{#each data.targets.filter(t=>t.name.toLowerCase().includes(searchQuery)) as target}<li><span>{target.name}</span><small>{data.apps.find(p=>p.id===target.app_id)?.sensitive?'敏感软件，已保护':!target.enabled?'已停用':!data.apps.find(p=>p.id===target.app_id)?.observe?'已保存 · 学习关闭':'已保存'}</small>{#if target.enabled&&!data.apps.find(p=>p.id===target.app_id)?.sensitive}<button class="text-button" aria-label={'从列表打开 '+target.name} disabled={busy} on:click={()=>openSaved(target.app_id)}>打开</button>{/if}{#if target.kind==='app'}<button class="text-button" aria-label={'移除 '+target.name} disabled={busy} on:click={()=>action('remove_target',{id:target.app_id})}>移除</button>{/if}</li>{:else}<li>没有匹配的已添加目标。</li>{/each}</ul></details>{/if}{#if !data.home_apps.length}<p class="friendly-note">这里还没有可显示的快捷入口。点击「添加应用」后会立即出现，无需等待学习。</p>{/if}</section>
 <div class="overview-grid"><section class="card"><h2>自动调节</h2><p>记住你喜欢的音量和外接屏亮度，下次轻轻调好。</p><button class="text-button" on:click={()=>tab='adjust'}>查看调节</button></section><section class="card"><h2>快速词</h2><p>常说的话自动排在前面，点一下输入。</p><button class="text-button" on:click={()=>tab='words'}>打开快速词</button></section></div>
 <p class="friendly-note">通常使用一两天就能积累初步习惯；同类场景出现得越多，建议越贴近你。</p>
 <ExperiencePanel {data} on:updated={e=>data=e.detail}/>
 {#if data.app_recommendation}<section class="card"><h2>你可能会用到</h2><p>要打开 {data.app_recommendation.app_name} 吗？</p><button class="secondary" disabled={busy||data.settings.paused} on:click={()=>action('launch_app',{id:data!.app_recommendation!.id})}>打开</button><button class="text-button" disabled={busy} on:click={()=>action('dismiss_app',{id:data!.app_recommendation!.id})}>这次不用</button></section>{/if}
 <AssistPanel {data} mode="ai"/>
 {#if data.demo}<details class="card"><summary>演示场景</summary><button class="secondary" disabled={busy} on:click={()=>action('demo_grid')}>加载示例应用</button><button class="secondary" disabled={busy} on:click={()=>action('demo_teach')}>加载音量习惯</button><select aria-label="模拟前台软件" on:change={e=>action('demo_scene',{scene:e.currentTarget.value})}><option value="game">游戏</option><option value="editor">编辑器</option><option value="browser">浏览器</option><option value="sensitive">敏感软件</option></select></details>{/if}
{:else if tab==='adjust'}
 <section class="page-heading"><div><h1>自动调节</h1><p>音量和外接屏亮度，一起照顾你的使用习惯。</p></div></section>
 <section class="card setting-row"><div><h2>按习惯自动微调</h2><p>无需逐次确认。每次最多调 5 个百分点，你手动改动时以你为准。</p></div><button class="toggle" class:on={data.settings.auto_adjustments} aria-label="自动调节总开关" aria-pressed={data.settings.auto_adjustments} disabled={busy} on:click={()=>settings({auto_adjustments:!data!.settings.auto_adjustments})}>{data.settings.auto_adjustments?'已开启':'开启'}</button></section>
 <section class="card"><h2>音量</h2><div class="volume-value">{data.volume==null?'—':Math.round(data.volume*100)}<small>%</small></div><p>在 Windows 中照常调节音量，Satori 会学习你的选择。</p><p class="friendly-note">{data.samples<3?'正在学习：需要几个不同场景中的稳定选择。':data.message}</p>{#if data.proposal}<button class="secondary" disabled={busy} on:click={()=>action('accept',{id:data!.proposal!.id})}>使用建议音量</button>{/if}{#each data.journal.filter(j=>j.undoable).slice(0,1) as j}<button class="text-button" disabled={busy} on:click={()=>action('undo',{id:j.id})}>撤销上次音量调节</button>{/each}</section>
 <AssistPanel {data} mode="adjust"/>
 <p class="friendly-note">三个独立场景中的偏好稳定后开始微调。敏感软件、暂停状态和不支持的设备会自动跳过。</p>
{:else if tab==='words'}<AssistPanel {data} mode="words"/>
{:else}
 <section class="page-heading"><div><h1>设置</h1><p>保持默认就可以，随时可以关闭。</p></div></section>
 <section class="card"><label class="setting-row"><span><strong>自动学习</strong><small>在本机记住常用应用、音量和亮度习惯</small></span><input type="checkbox" checked={data.settings.automatic_learning} disabled={busy} on:change={e=>settings({automatic_learning:e.currentTarget.checked})}></label><label class="setting-row"><span><strong>主动建议</strong><small>适当的时候，提示你可能会用到的应用</small></span><input type="checkbox" checked={data.settings.time_recommendations} disabled={busy} on:change={e=>settings({time_recommendations:e.currentTarget.checked,floating_cards:e.currentTarget.checked,associations:e.currentTarget.checked})}></label></section>
 <StartupControl startup={data.startup} {busy} onToggle={enabled=>action('set_startup',{enabled})}/>
 <section class="card"><h2>助手护栏</h2><p>密码和敏感输入不学习；不自动发送消息、删除文件、付款或运行命令。AI 只给候选建议，改变学习规则或打开程序须由你确认。</p><details><summary>不希望学习的软件</summary>{#each data.apps.filter(a=>!a.id.startsWith('web_')) as app}<label class="setting-row"><span>{app.name}{app.sensitive?' · 敏感软件，已保护':''}</span><input type="checkbox" aria-label={'学习 '+app.name} checked={app.observe&&!app.sensitive} disabled={busy||app.sensitive} on:change={e=>action('set_permission',{id:app.id,observe:e.currentTarget.checked,mode:e.currentTarget.checked?'auto':'off'})}></label>{/each}</details></section>
 <section class="card"><details><summary>网站与浏览器</summary><p>安装配套扩展与本机连接后，浏览器快速词与桌面共用开关和词库。</p><label class="setting-row"><span>学习常用网站（只记站点，不记页面内容）</span><input type="checkbox" checked={data.settings.website_observation} disabled={busy} on:change={e=>settings({website_observation:e.currentTarget.checked})}></label><div class="setting-row"><input aria-label="网站地址" placeholder="https://example.com" bind:value={website}><button class="secondary" disabled={busy||!website.trim()} on:click={()=>action('add_website',{url:website})}>添加常用网站</button></div></details><details><summary>清除学习记录</summary><p>清除应用、音量及例外经验后，从头开始了解你。快速词可在词库中单独删除。</p>{#if confirmForget}<button class="secondary" disabled={busy} on:click={async()=>{await action('forget');confirmForget=false;}}>确认清除</button><button class="text-button" on:click={()=>confirmForget=false}>取消</button>{:else}<button class="text-button" on:click={()=>confirmForget=true}>清除记录</button>{/if}</details></section>
{/if}
</div></main></div>
{/if}
<style>
.card{margin-bottom:20px}.friendly-note{color:#998aa4;font-size:14px;line-height:1.8}.setting-row{display:flex;align-items:center;justify-content:space-between;gap:22px;padding:16px 0}.setting-row small{display:block;color:#9b8ba6;font-size:13px;line-height:1.8}.setting-row input[type=checkbox]{width:20px;height:20px;accent-color:#9c71b0}.toggle{padding:12px 20px;border:0;border-radius:25px;background:#ece5f1;color:#846d91;cursor:pointer;white-space:nowrap}.toggle.on{background:#a074b8;color:white}.card.setting-row{padding:24px}.setting-row h2{margin-top:0}.search{width:100%;box-sizing:border-box;border:1px solid #e8dfed;border-radius:12px;padding:13px 16px;margin-bottom:15px;background:#fffdfd;color:#55455f}.volume-value{font-size:40px;color:#9772ac;margin:10px 0}.volume-value small{font-size:18px}details{margin:12px 0}summary{cursor:pointer;color:#8c719b;font-size:14px}select,input:not([type=checkbox]){max-width:100%}
.saved-targets ul{list-style:none;padding:0;margin:10px 0;max-height:280px;overflow:auto}.saved-targets li{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:10px 0;border-bottom:1px solid #f0e9f4}.saved-targets li span{overflow-wrap:anywhere;min-width:0;flex:1}.saved-targets li button{flex-shrink:0}.saved-targets li small{color:#998aa4;flex-shrink:0}
</style>
