<script lang="ts">
 import {onMount} from 'svelte';import {assist,type AssistStatus,type Request} from './assist-api';import type {Status} from './types';
 export let data:Status;export let mode:'words'|'adjust'|'ai'='words';
 let state:AssistStatus|null=null,error='',message='',busy=false,text='',limit=50,trial='',showPanel=false,composing=false,editor:HTMLTextAreaElement;
 let endpoint=localStorage.getItem('satori:ai-endpoint')??'',model=localStorage.getItem('satori:ai-model')??'',key='',prompt='',answer='';
 async function run(r:Request){if(busy)return;busy=true;error='';try{const next=await assist<AssistStatus>(r);state=next;limit=next.limit;return true;}catch(e){error=String(e);return false;}finally{busy=false;}}
 onMount(()=>{let alive=true;const refresh=async()=>{try{const next=await assist({op:"status"});if(alive&&!busy){state=next;}}catch(e){if(alive)error=String(e);}};run({op:'status'});const timer=setInterval(refresh,2000);return()=>{alive=false;clearInterval(timer);};});
 function insert(value:string){if(!state?.enabled||composing||data.settings.paused)return;const start=editor?.selectionStart??trial.length,end=editor?.selectionEnd??trial.length;trial=trial.slice(0,start)+value+trial.slice(end);showPanel=false;queueMicrotask(()=>{editor.focus();editor.setSelectionRange(start+value.length,start+value.length);});}
 async function ask(){busy=true;error='';try{answer=(await assist<{answer:string}>({op:'ask',prompt})).answer;}catch(e){error=String(e);}finally{busy=false;}}
 async function connect(){localStorage.setItem('satori:ai-endpoint',endpoint);localStorage.setItem('satori:ai-model',model);if(await run({op:'ai_mode',enabled:true,endpoint,model,key}))key='';}
</script>
{#if error}<p class="error" role="alert">{error}</p>{/if}{#if message}<p role="status">{message}</p>{/if}
{#if mode==='words'}
 <section class="page-heading"><div><h1>快速词</h1><p>常说的话，点一下就能输入。</p></div></section>
 <section class="card"><div class="row"><div><h2>学习并推荐常用词句</h2><p>开启后在本地学习，开始输入时在右下角显示推荐。</p></div><button class:active={state?.enabled} class="switch" aria-label="快速词总开关" aria-pressed={state?.enabled??false} disabled={busy||!state} on:click={()=>state&&run({op:'quick_words',enabled:!state.enabled})}>{state?.enabled?'已开启':'开启'}</button></div><p class="hint" role="status">{data.settings.paused?'助手已暂停，快速词也已暂停':state?.input_message}</p><p class="hint">不占用 Enter、Backspace 或输入法按键。密码、支付等敏感输入会跳过。</p></section>
 <section class="card"><h2>我的快速词</h2><p>常用词句重复出现后自动加入，越常用越靠前。</p><div class="word-list">{#each state?.words??[] as w}<div class="row"><span>{w.text}</span><button class="text-button" aria-label={'删除 '+w.text} disabled={busy} on:click={()=>run({op:'delete_word',text:w.text})}>删除</button></div>{/each}</div><details><summary>添加一句常用的话</summary><div class="row"><input aria-label="新快速词" placeholder="例如：好的，我稍后回复你。" bind:value={text} maxlength="120"><button class="secondary" disabled={busy||!text.trim()} on:click={async()=>{if(await run({op:'add_word',text}))text='';}}>添加</button></div></details><details><summary>保存数量</summary><label>最多保留 <input aria-label="快速词上限" type="number" min="1" max="200" bind:value={limit}> 条</label><button class="secondary" disabled={busy} on:click={()=>run({op:'limit',limit:Number(limit)})}>保存</button></details></section>
 <section class="card"><h2>试一下</h2><p>开启快速词后，在这里输入几个字，再点击右下角推荐。</p><textarea aria-label="快速词试写" bind:this={editor} bind:value={trial} on:input={()=>showPanel=!!state?.enabled&&!composing} on:compositionstart={()=>{composing=true;showPanel=false;}} on:compositionend={()=>{composing=false;showPanel=!!state?.enabled;}}></textarea><p class="hint">这里只演示点击输入。桌面软件支持普通可编辑文本框；浏览器使用配套扩展，共用此开关和词库。</p></section>
 {#if showPanel&&state?.enabled&&!data.settings.paused}<aside class="quick-word-popup" aria-label="快速词推荐"><strong>快速词 · 点一下输入</strong>{#each state.words.slice(0,6) as w}<button on:mousedown={e=>e.preventDefault()} on:click={()=>insert(w.text)}>{w.text}</button>{/each}</aside>{/if}
{:else if mode==='adjust'}
 <section class="card"><div class="row"><div><h2>外接屏亮度</h2><p>记住你在不同软件和时段的选择。</p></div><button class="text-button" disabled={busy} on:click={()=>run({op:'brightness_read'})}>刷新显示器</button></div>
 {#each state?.monitors??[] as m}<div class="monitor"><label for={m.id}>{m.name||'外接显示器'} · {m.value}%</label><input id={m.id} aria-label={'亮度 '+m.name} type="range" min="10" max="100" value={m.value} disabled={busy||data.settings.paused} on:change={e=>run({op:'brightness_set',device:m.id,before:m.value,value:Number(e.currentTarget.value)})}></div>{/each}
 {#if !state?.monitors.length}<p>未检测到可调节的外接显示器。请检查连接，并在显示器菜单中开启 DDC/CI。</p>{/if}<p class="hint" role="status">{state?.message}</p></section>
{:else}
 <section class="card" aria-label="可选 AI 增强"><div class="row"><div><h2>AI 增强 · 可选</h2><p>不连接也能使用全部本地功能。连接后，遇到陌生冲突或程序歧义才按需唤醒。</p></div>{#if state?.ai.enabled}<button class="switch active" aria-label="关闭AI增强" disabled={busy} on:click={()=>run({op:'ai_mode',enabled:false,endpoint:'',model:'',key:''})}>已开启</button>{/if}</div><p class="hint" role="status">{state?.ai.message}</p>
 {#if !state?.ai.enabled}<details><summary>连接 AI 服务</summary><label>接口地址<input aria-label="AI接口地址" placeholder="https://服务商/v1/chat/completions" bind:value={endpoint}></label><label>模型<input aria-label="AI模型" bind:value={model}></label><label>密钥<input aria-label="AI密钥" type="password" autocomplete="off" bind:value={key}></label><p class="hint">开启后，必要时会向你选择的服务发送软件名称、粗略时段、纠正次数和少量程序候选；不发送输入文字、文件路径或完整操作记录。密钥仅留在本次程序运行内存中，退出后需重新连接。</p><button class="secondary" disabled={busy||!key||!model||!endpoint||data.settings.paused} on:click={connect}>开启 AI 增强</button></details>{/if}
 {#if state?.ai.enabled}<details><summary>也可以主动问问 AI</summary><textarea aria-label="问问AI" placeholder="例如：怎样让晚上的屏幕看起来更舒服？" bind:value={prompt}></textarea><button class="primary" disabled={busy||!prompt.trim()||data.settings.paused} on:click={ask}>{busy?'正在回答…':'发送问题'}</button><p class="hint">主动发送只上传此处的问题。</p>{#if answer}<p class="answer">{answer}</p>{/if}</details>{/if}</section>
{/if}
<style>
.row{display:flex;align-items:center;justify-content:space-between;gap:20px}.card{margin-bottom:20px}.row h2{margin-top:0}.hint{font-size:13px;color:#8c7e98}.switch{min-width:92px;padding:12px 18px;border-radius:24px;border:0;background:#ece5f1;color:#80658f;font-weight:600;cursor:pointer}.switch.active{background:#a074b8;color:white}.word-list .row{padding:12px 0;border-bottom:1px solid #f0e9f4}.row input{flex:1}textarea,input{box-sizing:border-box;border:1px solid #e4daed;border-radius:10px;background:white;color:#45364e;padding:11px;max-width:100%}textarea{width:100%;min-height:110px;margin:12px 0}label{display:block;margin:12px 0}label input{margin:8px;display:block;width:100%}input[type=number]{display:inline;width:80px}input[type=range]{width:100%;accent-color:#a074b8}details{margin-top:18px}summary{cursor:pointer;color:#90729e;font-size:14px}.quick-word-popup{position:fixed;right:25px;bottom:25px;width:300px;border:1px solid #e2d5ec;background:#fcf8ff;padding:16px;box-shadow:0 10px 36px #42314c22;border-radius:16px;z-index:20}.quick-word-popup strong{font-size:13px;color:#9a82a8}.quick-word-popup button{display:block;text-align:left;width:100%;padding:12px;margin-top:8px;border:1px solid #eee3f4;border-radius:9px;background:white;color:#54425f;cursor:pointer}.answer{white-space:pre-wrap;line-height:1.8}
</style>
